services:
  pgdb:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: pgdb
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  aerich:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: >
      bash -c "
      aerich migrate &&\
      aerich upgrade
      "
    depends_on:
      pgdb:
        condition: service_healthy
